/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/{platform}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback that links a DSP account to the user */
        get: operations["dspCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{platform}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to a DSP to begin linking the account */
        get: operations["dspLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/federated/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete federated sign-in and start a session */
        get: operations["googleSignInCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/federated/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to Google to begin federated sign-in */
        get: operations["googleSignInStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a password reset link */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and reissue the session */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the signed-in user */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and start a session */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an email/password account */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address using an emailed token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List covers generated by the current user */
        get: operations["listCovers"];
        put?: never;
        /** Analyze a playlist and generate a cover */
        post: operations["generateCover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a generated cover by id */
        get: operations["getCover"];
        put?: never;
        post?: never;
        /** Delete a generated cover */
        delete: operations["deleteCover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's playlists for a DSP */
        get: operations["listPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ColorWeightResponse: {
            dimension: string;
            hexColor: string;
            weight: number;
        };
        CoverResponse: {
            createdAt: string;
            error?: string;
            id: string;
            imageUrl?: string;
            palette?: components["schemas"]["ColorWeightResponse"][];
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            playlistId: string;
            playlistName: string;
            prompt?: string;
            /** @enum {string} */
            status: "pending" | "analyzing" | "generating" | "ready" | "failed";
        };
        ForgotPasswordRequest: {
            email?: string;
        };
        GenerateCoverRequest: {
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            playlistId: string;
        };
        MessageResponse: {
            message?: string;
        };
        PlaylistResponse: {
            description: string;
            id: string;
            imageUrl?: string;
            name: string;
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            trackCount: number;
        };
        ProblemDetails: {
            detail?: string;
            instance?: string;
            status?: number;
            title?: string;
            type?: string;
        };
        ResetPasswordRequest: {
            newPassword?: string;
            token?: string;
        };
        SessionResponse: {
            csrfToken?: string;
            displayName?: string;
            email?: string;
            emailVerified?: boolean;
            userId?: string;
        };
        SignInRequest: {
            email?: string;
            password?: string;
        };
        SignUpRequest: {
            displayName?: string;
            email?: string;
            password?: string;
        };
        TokenRequest: {
            token?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dspCallback: {
        parameters: {
            query: {
                /**
                 * @description OAuth authorization code from the provider
                 * @example AQD...
                 */
                code: string;
                /**
                 * @description Opaque value echoed back by the provider
                 * @example xY...
                 */
                state?: string;
            };
            header?: never;
            path: {
                /**
                 * @description DSP platform: spotify, apple_music, youtube_music
                 * @example spotify
                 */
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 302 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dspLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description DSP platform: spotify, apple_music, youtube_music
                 * @example spotify
                 */
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 302 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleSignInCallback: {
        parameters: {
            query?: {
                /**
                 * @description Authorization code from Google
                 * @example 4/0A...
                 */
                code?: string;
                /**
                 * @description Opaque value echoed back by Google
                 * @example xY...
                 */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 302 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    googleSignInStart: {
        parameters: {
            query?: {
                /**
                 * @description Path within the app to return to afterwards
                 * @example /covers
                 */
                return?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response 302 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response 501 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": ""
                 *     }
                 */
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "token": "",
                 *       "newpassword": ""
                 *     }
                 */
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userid": "",
                     *       "email": "",
                     *       "displayname": "",
                     *       "emailverified": false,
                     *       "csrftoken": ""
                     *     }
                     */
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userid": "",
                     *       "email": "",
                     *       "displayname": "",
                     *       "emailverified": false,
                     *       "csrftoken": ""
                     *     }
                     */
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "",
                 *       "password": ""
                 *     }
                 */
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userid": "",
                     *       "email": "",
                     *       "displayname": "",
                     *       "emailverified": false,
                     *       "csrftoken": ""
                     *     }
                     */
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "",
                 *       "password": "",
                 *       "displayname": ""
                 *     }
                 */
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Response 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "token": ""
                 *     }
                 */
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": ""
                     *     }
                     */
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    listCovers: {
        parameters: {
            query?: {
                /**
                 * @description Filter to one lifecycle status (empty = all)
                 * @example ready
                 */
                status?: string;
                /**
                 * @description Page size (default 20, max 100)
                 * @example 20
                 */
                limit?: string;
                /**
                 * @description Rows to skip
                 * @example 0
                 */
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["CoverResponse"][];
                };
            };
        };
    };
    generateCover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "platform": "",
                 *       "playlistid": ""
                 *     }
                 */
                "application/json": components["schemas"]["GenerateCoverRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "",
                     *       "status": "",
                     *       "platform": "",
                     *       "playlistid": "",
                     *       "playlistname": "",
                     *       "imageurl": "",
                     *       "prompt": "",
                     *       "palette": [],
                     *       "error": "",
                     *       "createdat": ""
                     *     }
                     */
                    "application/json": components["schemas"]["CoverResponse"];
                };
            };
        };
    };
    getCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Cover id
                 * @example 000000000000000000000000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "",
                     *       "status": "",
                     *       "platform": "",
                     *       "playlistid": "",
                     *       "playlistname": "",
                     *       "imageurl": "",
                     *       "prompt": "",
                     *       "palette": [],
                     *       "error": "",
                     *       "createdat": ""
                     *     }
                     */
                    "application/json": components["schemas"]["CoverResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Cover id
                 * @example 000000000000000000000000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listPlaylists: {
        parameters: {
            query: {
                /**
                 * @description DSP platform
                 * @example spotify
                 */
                platform: string;
                /**
                 * @description Case-insensitive search over name and description
                 * @example coffee
                 */
                q?: string;
                /**
                 * @description Ordering: name or tracks
                 * @example name
                 */
                sort?: string;
                /**
                 * @description Page size (default 20, max 100)
                 * @example 20
                 */
                limit?: string;
                /**
                 * @description Rows to skip
                 * @example 0
                 */
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["PlaylistResponse"][];
                };
            };
        };
    };
}
