/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/{platform}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback that links a DSP account to the user */
        get: operations["dspCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/{platform}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the OAuth authorization URL for a DSP */
        get: operations["dspLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List covers generated by the current user */
        get: operations["listCovers"];
        put?: never;
        /** Analyze a playlist and generate a cover */
        post: operations["generateCover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a generated cover by id */
        get: operations["getCover"];
        put?: never;
        post?: never;
        /** Delete a generated cover */
        delete: operations["deleteCover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's playlists for a DSP */
        get: operations["listPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ColorWeightResponse: {
            dimension: string;
            hexColor: string;
            weight: number;
        };
        CoverResponse: {
            createdAt: string;
            error?: string;
            id: string;
            imageUrl?: string;
            palette?: components["schemas"]["ColorWeightResponse"][];
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            playlistId: string;
            playlistName: string;
            prompt?: string;
            /** @enum {string} */
            status: "pending" | "analyzing" | "generating" | "ready" | "failed";
        };
        GenerateCoverRequest: {
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            playlistId: string;
        };
        PlaylistResponse: {
            description: string;
            id: string;
            imageUrl?: string;
            name: string;
            /** @enum {string} */
            platform: "spotify" | "apple_music" | "youtube_music";
            trackCount: number;
        };
        ProblemDetails: {
            detail?: string;
            instance?: string;
            status?: number;
            title?: string;
            type?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dspCallback: {
        parameters: {
            query: {
                /**
                 * @description OAuth authorization code from the provider
                 * @example AQD...
                 */
                code: string;
            };
            header?: never;
            path: {
                /**
                 * @description DSP platform: spotify, apple_music, youtube_music
                 * @example spotify
                 */
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dspLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description DSP platform: spotify, apple_music, youtube_music
                 * @example spotify
                 */
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCovers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["CoverResponse"][];
                };
            };
        };
    };
    generateCover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "platform": "",
                 *       "playlistid": ""
                 *     }
                 */
                "application/json": components["schemas"]["GenerateCoverRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "",
                     *       "status": "",
                     *       "platform": "",
                     *       "playlistid": "",
                     *       "playlistname": "",
                     *       "imageurl": "",
                     *       "prompt": "",
                     *       "palette": [],
                     *       "error": "",
                     *       "createdat": ""
                     *     }
                     */
                    "application/json": components["schemas"]["CoverResponse"];
                };
            };
        };
    };
    getCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Cover id
                 * @example 000000000000000000000000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "",
                     *       "status": "",
                     *       "platform": "",
                     *       "playlistid": "",
                     *       "playlistname": "",
                     *       "imageurl": "",
                     *       "prompt": "",
                     *       "palette": [],
                     *       "error": "",
                     *       "createdat": ""
                     *     }
                     */
                    "application/json": components["schemas"]["CoverResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Cover id
                 * @example 000000000000000000000000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "",
                     *       "title": "",
                     *       "status": 0,
                     *       "detail": "",
                     *       "instance": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listPlaylists: {
        parameters: {
            query: {
                /**
                 * @description DSP platform
                 * @example spotify
                 */
                platform: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["PlaylistResponse"][];
                };
            };
        };
    };
}
