// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :execrows
UPDATE email_tokens SET consumed_at = $2 WHERE token_hash = $1 AND consumed_at IS NULL
`

type ConsumeEmailTokenParams struct {
	TokenHash  []byte
	ConsumedAt pgtype.Timestamptz
}

// Single-use: the consumed_at IS NULL guard means a replayed link affects zero
// rows, so the caller can reject it without a separate read.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailToken, arg.TokenHash, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, user_id, purpose, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailTokenParams struct {
	TokenHash []byte
	UserID    string
	Purpose   string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, session_id, issued_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	TokenHash []byte
	SessionID string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.TokenHash,
		arg.SessionID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, issued_at, last_used_at, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	IssuedAt   pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  string
	Ip         string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.IssuedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const deleteCredentialByUser = `-- name: DeleteCredentialByUser :exec
DELETE FROM user_credentials WHERE user_id = $1
`

func (q *Queries) DeleteCredentialByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteCredentialByUser, userID)
	return err
}

const deleteEmailTokensByUserPurpose = `-- name: DeleteEmailTokensByUserPurpose :exec
DELETE FROM email_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailTokensByUserPurposeParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) DeleteEmailTokensByUserPurpose(ctx context.Context, arg DeleteEmailTokensByUserPurposeParams) error {
	_, err := q.db.Exec(ctx, deleteEmailTokensByUserPurpose, arg.UserID, arg.Purpose)
	return err
}

const deleteRefreshTokensBySession = `-- name: DeleteRefreshTokensBySession :exec
DELETE FROM refresh_tokens WHERE session_id = $1
`

func (q *Queries) DeleteRefreshTokensBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensBySession, sessionID)
	return err
}

const getCredentialByUser = `-- name: GetCredentialByUser :one
SELECT user_id, password_hash, updated_at
FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) GetCredentialByUser(ctx context.Context, userID string) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUser, userID)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT token_hash, user_id, purpose, expires_at, consumed_at, created_at
FROM email_tokens
WHERE token_hash = $1
`

func (q *Queries) GetEmailToken(ctx context.Context, tokenHash []byte) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailToken, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT provider, subject, user_id, email, created_at
FROM user_identities
WHERE provider = $1 AND subject = $2
`

type GetIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT rt.token_hash, rt.session_id, rt.issued_at, rt.expires_at, rt.used_at,
       s.user_id, s.expires_at AS session_expires_at, s.revoked_at AS session_revoked_at
FROM refresh_tokens rt
JOIN sessions s ON s.id = rt.session_id
WHERE rt.token_hash = $1
`

type GetRefreshTokenRow struct {
	TokenHash        []byte
	SessionID        string
	IssuedAt         pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	UsedAt           pgtype.Timestamptz
	UserID           string
	SessionExpiresAt pgtype.Timestamptz
	SessionRevokedAt pgtype.Timestamptz
}

// Joined to sessions so a single round trip yields both the token's state and
// whether the session behind it is still alive.
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UserID,
		&i.SessionExpiresAt,
		&i.SessionRevokedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, issued_at, last_used_at, expires_at, revoked_at, user_agent, ip
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT provider, subject, user_id, email, created_at
FROM user_identities
WHERE user_id = $1
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID string) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.Provider,
			&i.Subject,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE refresh_tokens SET used_at = $2 WHERE token_hash = $1 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	TokenHash []byte
	UsedAt    pgtype.Timestamptz
}

// Guarded by used_at IS NULL so two concurrent refreshes cannot both succeed:
// the loser affects zero rows and is treated as reuse.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.TokenHash, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $2 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeSessionsByUser = `-- name: RevokeSessionsByUser :exec
UPDATE sessions SET revoked_at = $2 WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeSessionsByUserParams struct {
	UserID    string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSessionsByUser(ctx context.Context, arg RevokeSessionsByUserParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUser, arg.UserID, arg.RevokedAt)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users SET email_verified = $2, updated_at = $3 WHERE id = $1
`

type SetUserEmailVerifiedParams struct {
	ID            string
	EmailVerified bool
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, arg.ID, arg.EmailVerified, arg.UpdatedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID         string
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastUsedAt)
	return err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO user_credentials (user_id, password_hash, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    updated_at = EXCLUDED.updated_at
`

type UpsertCredentialParams struct {
	UserID       string
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	return err
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO user_identities (provider, subject, user_id, email, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, subject) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    email = EXCLUDED.email
`

type UpsertIdentityParams struct {
	Provider  string
	Subject   string
	UserID    string
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}
