// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCover = `-- name: DeleteCover :execrows
DELETE FROM covers
WHERE id = $1 AND user_id = $2
`

type DeleteCoverParams struct {
	ID     string
	UserID string
}

// Scoped to the owner so a user can never delete another user's cover; the
// rows-affected count lets the caller distinguish "deleted" from "not found".
func (q *Queries) DeleteCover(ctx context.Context, arg DeleteCoverParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCover, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStuckCovers = `-- name: FailStuckCovers :execrows
UPDATE covers
SET status     = 'failed',
    error      = 'generation was interrupted, try again',
    updated_at = now()
WHERE status IN ('pending', 'analyzing', 'generating')
  AND updated_at < $1
`

// Generation runs in-process (ADR 0019), so a crash or instance scale-down
// orphans any in-flight cover in a non-terminal status, and the gallery would
// poll it as "generating" forever. Every pipeline stage bumps updated_at, so a
// non-terminal cover untouched since before the cutoff has no worker attached.
func (q *Queries) FailStuckCovers(ctx context.Context, staleBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, failStuckCovers, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCoverByID = `-- name: GetCoverByID :one
SELECT id, user_id, platform, playlist_id, playlist_name, status,
       prompt, image_url, analysis, error, created_at, updated_at
FROM covers
WHERE id = $1
`

func (q *Queries) GetCoverByID(ctx context.Context, id string) (Cover, error) {
	row := q.db.QueryRow(ctx, getCoverByID, id)
	var i Cover
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlaylistID,
		&i.PlaylistName,
		&i.Status,
		&i.Prompt,
		&i.ImageUrl,
		&i.Analysis,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoversByUser = `-- name: ListCoversByUser :many
SELECT id, user_id, platform, playlist_id, playlist_name, status,
       prompt, image_url, analysis, error, created_at, updated_at
FROM covers
WHERE user_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListCoversByUserParams struct {
	UserID    string
	Status    string
	RowOffset int32
	RowLimit  int32
}

// An empty @status returns every lifecycle state; otherwise it filters to one.
func (q *Queries) ListCoversByUser(ctx context.Context, arg ListCoversByUserParams) ([]Cover, error) {
	rows, err := q.db.Query(ctx, listCoversByUser,
		arg.UserID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cover{}
	for rows.Next() {
		var i Cover
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlaylistID,
			&i.PlaylistName,
			&i.Status,
			&i.Prompt,
			&i.ImageUrl,
			&i.Analysis,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCover = `-- name: UpsertCover :exec
INSERT INTO covers (
    id, user_id, platform, playlist_id, playlist_name, status,
    prompt, image_url, analysis, error, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    playlist_id = EXCLUDED.playlist_id,
    playlist_name = EXCLUDED.playlist_name,
    status = EXCLUDED.status,
    prompt = EXCLUDED.prompt,
    image_url = EXCLUDED.image_url,
    analysis = EXCLUDED.analysis,
    error = EXCLUDED.error,
    updated_at = EXCLUDED.updated_at
`

type UpsertCoverParams struct {
	ID           string
	UserID       string
	Platform     string
	PlaylistID   string
	PlaylistName string
	Status       string
	Prompt       string
	ImageUrl     string
	Analysis     []byte
	Error        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCover(ctx context.Context, arg UpsertCoverParams) error {
	_, err := q.db.Exec(ctx, upsertCover,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.PlaylistID,
		arg.PlaylistName,
		arg.Status,
		arg.Prompt,
		arg.ImageUrl,
		arg.Analysis,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
