// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCoverByID = `-- name: GetCoverByID :one
SELECT id, user_id, platform, playlist_id, playlist_name, status,
       prompt, image_url, analysis, error, created_at, updated_at
FROM covers
WHERE id = $1
`

func (q *Queries) GetCoverByID(ctx context.Context, id string) (Cover, error) {
	row := q.db.QueryRow(ctx, getCoverByID, id)
	var i Cover
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlaylistID,
		&i.PlaylistName,
		&i.Status,
		&i.Prompt,
		&i.ImageUrl,
		&i.Analysis,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoversByUser = `-- name: ListCoversByUser :many
SELECT id, user_id, platform, playlist_id, playlist_name, status,
       prompt, image_url, analysis, error, created_at, updated_at
FROM covers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCoversByUserParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListCoversByUser(ctx context.Context, arg ListCoversByUserParams) ([]Cover, error) {
	rows, err := q.db.Query(ctx, listCoversByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cover{}
	for rows.Next() {
		var i Cover
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlaylistID,
			&i.PlaylistName,
			&i.Status,
			&i.Prompt,
			&i.ImageUrl,
			&i.Analysis,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCover = `-- name: UpsertCover :exec
INSERT INTO covers (
    id, user_id, platform, playlist_id, playlist_name, status,
    prompt, image_url, analysis, error, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    playlist_id = EXCLUDED.playlist_id,
    playlist_name = EXCLUDED.playlist_name,
    status = EXCLUDED.status,
    prompt = EXCLUDED.prompt,
    image_url = EXCLUDED.image_url,
    analysis = EXCLUDED.analysis,
    error = EXCLUDED.error,
    updated_at = EXCLUDED.updated_at
`

type UpsertCoverParams struct {
	ID           string
	UserID       string
	Platform     string
	PlaylistID   string
	PlaylistName string
	Status       string
	Prompt       string
	ImageUrl     string
	Analysis     []byte
	Error        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCover(ctx context.Context, arg UpsertCoverParams) error {
	_, err := q.db.Exec(ctx, upsertCover,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.PlaylistID,
		arg.PlaylistName,
		arg.Status,
		arg.Prompt,
		arg.ImageUrl,
		arg.Analysis,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
