// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cover_images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findCoverImage = `-- name: FindCoverImage :one
SELECT bytes, content_type
FROM cover_images
WHERE revision_id = $1
`

type FindCoverImageRow struct {
	Bytes       []byte
	ContentType string
}

func (q *Queries) FindCoverImage(ctx context.Context, revisionID string) (FindCoverImageRow, error) {
	row := q.db.QueryRow(ctx, findCoverImage, revisionID)
	var i FindCoverImageRow
	err := row.Scan(&i.Bytes, &i.ContentType)
	return i, err
}

const saveCoverImage = `-- name: SaveCoverImage :exec
INSERT INTO cover_images (revision_id, bytes, content_type, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (revision_id) DO UPDATE SET
    bytes = EXCLUDED.bytes,
    content_type = EXCLUDED.content_type,
    created_at = EXCLUDED.created_at
`

type SaveCoverImageParams struct {
	RevisionID  string
	Bytes       []byte
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

// Keyed by revision, so each run keeps its own bytes and they cascade with it.
// Still an upsert, so a retried store replaces the bytes rather than failing on
// the primary key.
func (q *Queries) SaveCoverImage(ctx context.Context, arg SaveCoverImageParams) error {
	_, err := q.db.Exec(ctx, saveCoverImage,
		arg.RevisionID,
		arg.Bytes,
		arg.ContentType,
		arg.CreatedAt,
	)
	return err
}
