// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dsp_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConnectionsByUser = `-- name: DeleteConnectionsByUser :exec
DELETE FROM dsp_connections
WHERE user_id = $1
`

func (q *Queries) DeleteConnectionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteConnectionsByUser, userID)
	return err
}

const listConnectionsByUser = `-- name: ListConnectionsByUser :many
SELECT user_id, platform, provider_user_id, access_token, refresh_token, expires_at, scopes
FROM dsp_connections
WHERE user_id = $1
`

func (q *Queries) ListConnectionsByUser(ctx context.Context, userID string) ([]DspConnection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DspConnection{}
	for rows.Next() {
		var i DspConnection
		if err := rows.Scan(
			&i.UserID,
			&i.Platform,
			&i.ProviderUserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDSPConnection = `-- name: UpsertDSPConnection :exec
INSERT INTO dsp_connections (
    user_id, platform, provider_user_id, access_token, refresh_token, expires_at, scopes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, platform) DO UPDATE SET
    provider_user_id = EXCLUDED.provider_user_id,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at = EXCLUDED.expires_at,
    scopes = EXCLUDED.scopes
`

type UpsertDSPConnectionParams struct {
	UserID         string
	Platform       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	Scopes         []string
}

func (q *Queries) UpsertDSPConnection(ctx context.Context, arg UpsertDSPConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertDSPConnection,
		arg.UserID,
		arg.Platform,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	return err
}
