// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lyrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLyricsByKeys = `-- name: FindLyricsByKeys :many
SELECT track_key, lyrics, found, fetched_at
FROM lyrics_cache
WHERE track_key = ANY($1::TEXT[])
`

// One round trip for a whole playlist. Looking these up one key at a time is
// what this table exists to avoid: a 194-track playlist would otherwise open
// 194 conversations with the database before doing any work.
func (q *Queries) FindLyricsByKeys(ctx context.Context, keys []string) ([]LyricsCache, error) {
	rows, err := q.db.Query(ctx, findLyricsByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LyricsCache{}
	for rows.Next() {
		var i LyricsCache
		if err := rows.Scan(
			&i.TrackKey,
			&i.Lyrics,
			&i.Found,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLyrics = `-- name: SaveLyrics :exec
INSERT INTO lyrics_cache (track_key, lyrics, found, fetched_at)
SELECT
    unnest($1::TEXT[]),
    unnest($2::TEXT[]),
    unnest($3::BOOLEAN[]),
    unnest($4::TIMESTAMPTZ[])
ON CONFLICT (track_key) DO UPDATE SET
    lyrics = EXCLUDED.lyrics,
    found = EXCLUDED.found,
    fetched_at = EXCLUDED.fetched_at
`

type SaveLyricsParams struct {
	Keys      []string
	Lyrics    []string
	Found     []bool
	FetchedAt []pgtype.Timestamptz
}

// Batched upsert, so a generation writes once however many misses it had.
// ON CONFLICT overwrites rather than skipping, which is what lets a negative
// entry become a positive one when lrclib later gains the track.
func (q *Queries) SaveLyrics(ctx context.Context, arg SaveLyricsParams) error {
	_, err := q.db.Exec(ctx, saveLyrics,
		arg.Keys,
		arg.Lyrics,
		arg.Found,
		arg.FetchedAt,
	)
	return err
}
