// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthBlock struct {
	Ip         string
	Identifier string
	BlockedAt  pgtype.Timestamptz
	Failures   int32
	Reason     string
}

type Cover struct {
	ID           string
	UserID       string
	Platform     string
	PlaylistID   string
	PlaylistName string
	Status       string
	Error        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CoverImage struct {
	RevisionID  string
	Bytes       []byte
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

type CoverRevision struct {
	ID             string
	CoverID        string
	RevisionNumber int32
	Status         string
	Prompt         string
	Analysis       []byte
	Error          string
	CompletedAt    pgtype.Timestamptz
}

type DspConnection struct {
	UserID         string
	Platform       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	Scopes         []string
}

type EmailToken struct {
	TokenHash  []byte
	UserID     string
	Purpose    string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type LyricsCache struct {
	TrackKey  string
	Lyrics    string
	Found     bool
	FetchedAt pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash []byte
	SessionID string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	IssuedAt   pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	UserAgent  string
	Ip         string
}

type TrackFeature struct {
	TrackKey        string
	Present         bool
	Danceability    float64
	Acousticness    float64
	Energy          float64
	Valence         float64
	FetchedAt       pgtype.Timestamptz
	OnsetRate       float64
	FeaturesVersion int32
}

type User struct {
	ID            string
	Email         string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	EmailVerified bool
}

type UserCredential struct {
	UserID       string
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type UserIdentity struct {
	Provider  string
	Subject   string
	UserID    string
	Email     string
	CreatedAt pgtype.Timestamptz
}
