// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cover struct {
	ID           string
	UserID       string
	Platform     string
	PlaylistID   string
	PlaylistName string
	Status       string
	Prompt       string
	ImageUrl     string
	Analysis     []byte
	Error        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DspConnection struct {
	UserID         string
	Platform       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	Scopes         []string
}

type EmailToken struct {
	TokenHash  []byte
	UserID     string
	Purpose    string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash []byte
	SessionID string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	IssuedAt   pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	UserAgent  string
	Ip         string
}

type User struct {
	ID            string
	Email         string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	EmailVerified bool
}

type UserCredential struct {
	UserID       string
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type UserIdentity struct {
	Provider  string
	Subject   string
	UserID    string
	Email     string
	CreatedAt pgtype.Timestamptz
}
