// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cover struct {
	ID           string
	UserID       string
	Platform     string
	PlaylistID   string
	PlaylistName string
	Status       string
	Prompt       string
	ImageUrl     string
	Analysis     []byte
	Error        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DspConnection struct {
	UserID         string
	Platform       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   string
	ExpiresAt      pgtype.Timestamptz
	Scopes         []string
}

type User struct {
	ID          string
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
