// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteConnectionsByUser(ctx context.Context, userID string) error
	GetCoverByID(ctx context.Context, id string) (Cover, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListConnectionsByUser(ctx context.Context, userID string) ([]DspConnection, error)
	ListCoversByUser(ctx context.Context, arg ListCoversByUserParams) ([]Cover, error)
	UpsertCover(ctx context.Context, arg UpsertCoverParams) error
	UpsertDSPConnection(ctx context.Context, arg UpsertDSPConnectionParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
