// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteConnectionsByUser(ctx context.Context, userID string) error
	// Scoped to the owner so a user can never delete another user's cover; the
	// rows-affected count lets the caller distinguish "deleted" from "not found".
	DeleteCover(ctx context.Context, arg DeleteCoverParams) (int64, error)
	GetCoverByID(ctx context.Context, id string) (Cover, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListConnectionsByUser(ctx context.Context, userID string) ([]DspConnection, error)
	// An empty @status returns every lifecycle state; otherwise it filters to one.
	ListCoversByUser(ctx context.Context, arg ListCoversByUserParams) ([]Cover, error)
	UpsertCover(ctx context.Context, arg UpsertCoverParams) error
	UpsertDSPConnection(ctx context.Context, arg UpsertDSPConnectionParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
