// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_features.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findTrackFeaturesByKeys = `-- name: FindTrackFeaturesByKeys :many
SELECT track_key, present, danceability, acousticness, energy, valence, onset_rate, features_version, fetched_at
FROM track_features
WHERE track_key = ANY($1::TEXT[])
`

type FindTrackFeaturesByKeysRow struct {
	TrackKey        string
	Present         bool
	Danceability    float64
	Acousticness    float64
	Energy          float64
	Valence         float64
	OnsetRate       float64
	FeaturesVersion int32
	FetchedAt       pgtype.Timestamptz
}

// One round trip for a whole playlist, as with lyrics.
func (q *Queries) FindTrackFeaturesByKeys(ctx context.Context, keys []string) ([]FindTrackFeaturesByKeysRow, error) {
	rows, err := q.db.Query(ctx, findTrackFeaturesByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTrackFeaturesByKeysRow{}
	for rows.Next() {
		var i FindTrackFeaturesByKeysRow
		if err := rows.Scan(
			&i.TrackKey,
			&i.Present,
			&i.Danceability,
			&i.Acousticness,
			&i.Energy,
			&i.Valence,
			&i.OnsetRate,
			&i.FeaturesVersion,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTrackFeatures = `-- name: SaveTrackFeatures :exec
INSERT INTO track_features (
    track_key, present, danceability, acousticness, energy, valence, onset_rate, features_version, fetched_at
)
SELECT
    unnest($1::TEXT[]),
    unnest($2::BOOLEAN[]),
    unnest($3::DOUBLE PRECISION[]),
    unnest($4::DOUBLE PRECISION[]),
    unnest($5::DOUBLE PRECISION[]),
    unnest($6::DOUBLE PRECISION[]),
    unnest($7::DOUBLE PRECISION[]),
    unnest($8::INTEGER[]),
    unnest($9::TIMESTAMPTZ[])
ON CONFLICT (track_key) DO UPDATE SET
    present = EXCLUDED.present,
    danceability = EXCLUDED.danceability,
    acousticness = EXCLUDED.acousticness,
    energy = EXCLUDED.energy,
    valence = EXCLUDED.valence,
    onset_rate = EXCLUDED.onset_rate,
    features_version = EXCLUDED.features_version,
    fetched_at = EXCLUDED.fetched_at
`

type SaveTrackFeaturesParams struct {
	Keys            []string
	Present         []bool
	Danceability    []float64
	Acousticness    []float64
	Energy          []float64
	Valence         []float64
	OnsetRate       []float64
	FeaturesVersion []int32
	FetchedAt       []pgtype.Timestamptz
}

// Batched upsert. ON CONFLICT overwrites rather than skipping, so a negative
// entry becomes positive once MusicBrainz gains the release.
func (q *Queries) SaveTrackFeatures(ctx context.Context, arg SaveTrackFeaturesParams) error {
	_, err := q.db.Exec(ctx, saveTrackFeatures,
		arg.Keys,
		arg.Present,
		arg.Danceability,
		arg.Acousticness,
		arg.Energy,
		arg.Valence,
		arg.OnsetRate,
		arg.FeaturesVersion,
		arg.FetchedAt,
	)
	return err
}
