// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, display_name, created_at, updated_at, email_verified)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID            string
	Email         string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	EmailVerified bool
}

// Unlike UpsertUser this does write email_verified. Creation is the one moment
// the value is being asserted rather than saved back, so there is no earlier
// read to go stale: the caller is stating what the row is born as. UpsertUser
// still refuses to carry the column, which is what stops a stale in-memory User
// from silently un-verifying an account later.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EmailVerified,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, created_at, updated_at, email_verified
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, created_at, updated_at, email_verified
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, email, display_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    updated_at = EXCLUDED.updated_at
`

type UpsertUserParams struct {
	ID          string
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Deliberately does not write email_verified. Verification state is owned by
// SetUserEmailVerified (see auth.sql); if a general-purpose user save could
// carry it, a stale in-memory User would silently un-verify an account.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
