// Package http builds the mux router for the Aurify API and wires it to the
// application layer. Routes are grouped so the write side (commands) and read
// side (queries) read clearly, and each is documented for OpenAPI generation.
package http

import (
	"context"

	"github.com/fgrzl/mux"

	"github.com/phillipjad/aurify/backend/internal/app"
	"github.com/phillipjad/aurify/backend/internal/app/ports"
	"github.com/phillipjad/aurify/backend/internal/transport/http/dto"
	"github.com/phillipjad/aurify/backend/internal/transport/http/handlers"
)

// API-level OpenAPI metadata. version is supplied at call time (stamped into
// the binary); title and description are stable.
const (
	apiTitle       = "Aurify API"
	apiDescription = "Generate abstract covers from a playlist's audio features and lyric sentiment."
)

// NewRouter builds the fully configured API router. version is reported in the
// OpenAPI info object (defaults to "dev" when empty).
//
// ready is the readiness check used by GET /readyz (e.g. a PostgreSQL ping); pass
// nil to always report ready.
func NewRouter(
	application *app.App,
	providers ports.DSPRegistry,
	version string,
	corsOrigins []string,
	ready func(context.Context) error,
) (*mux.Router, error) {
	if version == "" {
		version = "dev"
	}
	router := mux.NewRouter(
		mux.WithTitle(apiTitle),
		mux.WithVersion(version),
		mux.WithDescription(apiDescription),
	)

	mux.UseLogging(router)
	mux.UseCompression(router)
	if len(corsOrigins) > 0 {
		mux.UseCORS(router,
			mux.WithCORSAllowedOrigins(corsOrigins...),
			mux.WithCORSAllowedMethods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"),
			mux.WithCORSAllowedHeaders("Content-Type", "Authorization", "X-User-ID"),
			mux.WithCORSCredentials(true),
		)
	}

	auth := handlers.NewAuth(application, providers)
	playlists := handlers.NewPlaylists(application)
	covers := handlers.NewCovers(application)

	err := router.Configure(func(r *mux.Router) {
		// Kubernetes-style probes (provided by mux).
		r.Livez()
		r.ReadyzWithCheck(func(c mux.RouteContext) bool {
			if ready == nil {
				return true
			}
			return ready(c) == nil
		})

		api := r.Group("/api/v1")
		api.WithTags("aurify")

		// ---- write side (commands) ----
		api.GET("/auth/{platform}/login", auth.Login).
			AllowAnonymous().
			WithOperationID("dspLogin").
			WithSummary("Get the OAuth authorization URL for a DSP").
			WithPathParam("platform", "DSP platform: spotify, apple_music, youtube_music", "spotify")

		api.GET("/auth/{platform}/callback", auth.Callback).
			AllowAnonymous().
			WithOperationID("dspCallback").
			WithSummary("OAuth callback that links a DSP account to the user").
			WithPathParam("platform", "DSP platform: spotify, apple_music, youtube_music", "spotify").
			WithRequiredQueryParam("code", "OAuth authorization code from the provider", "AQD...")

		api.POST("/covers", covers.Generate).
			WithOperationID("generateCover").
			WithSummary("Analyze a playlist and generate a cover").
			WithJSONBody(dto.GenerateCoverRequest{}).
			WithCreatedResponse(dto.CoverResponse{})

		// ---- read side (queries) ----
		api.GET("/playlists", playlists.List).
			WithOperationID("listPlaylists").
			WithSummary("List the current user's playlists for a DSP").
			WithRequiredQueryParam("platform", "DSP platform", "spotify").
			WithQueryParam("q", "Case-insensitive search over name and description", "coffee").
			WithQueryParam("sort", "Ordering: name or tracks", "name").
			WithQueryParam("limit", "Page size (default 20, max 100)", "20").
			WithQueryParam("offset", "Rows to skip", "0").
			WithOKResponse([]dto.PlaylistResponse{})

		api.GET("/covers", covers.List).
			WithOperationID("listCovers").
			WithSummary("List covers generated by the current user").
			WithQueryParam("status", "Filter to one lifecycle status (empty = all)", "ready").
			WithQueryParam("limit", "Page size (default 20, max 100)", "20").
			WithQueryParam("offset", "Rows to skip", "0").
			WithOKResponse([]dto.CoverResponse{})

		api.GET("/covers/{id}", covers.Get).
			WithOperationID("getCover").
			WithSummary("Get a generated cover by id").
			WithPathParam("id", "Cover id", "000000000000000000000000").
			WithOKResponse(dto.CoverResponse{}).
			WithResponse(404, mux.ProblemDetails{})

		api.DELETE("/covers/{id}", covers.Delete).
			WithOperationID("deleteCover").
			WithSummary("Delete a generated cover").
			WithPathParam("id", "Cover id", "000000000000000000000000").
			WithNoContentResponse().
			WithResponse(404, mux.ProblemDetails{})

		// Serve the SPA for all non-API routes. Two registrations are required:
		// "" catches the root ("/") and "/**" catches every deeper path.
		// Both must come after API routes so that specific paths take priority.
		spa := newSPAHandler()
		r.Handle("GET", "", spa).AllowAnonymous()
		r.Handle("GET", "/**", spa).AllowAnonymous()
	})
	if err != nil {
		return nil, err
	}
	return router, nil
}
