/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as CoversRouteImport } from './routes/covers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoversIndexRouteImport } from './routes/covers.index'
import { Route as CoversCoverIdRouteImport } from './routes/covers.$coverId'

const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversRoute = CoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversIndexRoute = CoversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoversRoute,
} as any)
const CoversCoverIdRoute = CoversCoverIdRouteImport.update({
  id: '/$coverId',
  path: '/$coverId',
  getParentRoute: () => CoversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/covers': typeof CoversRouteWithChildren
  '/playlists': typeof PlaylistsRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/covers/': typeof CoversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/covers': typeof CoversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/covers': typeof CoversRouteWithChildren
  '/playlists': typeof PlaylistsRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/covers/': typeof CoversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/covers' | '/playlists' | '/covers/$coverId' | '/covers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playlists' | '/covers/$coverId' | '/covers'
  id:
    | '__root__'
    | '/'
    | '/covers'
    | '/playlists'
    | '/covers/$coverId'
    | '/covers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoversRoute: typeof CoversRouteWithChildren
  PlaylistsRoute: typeof PlaylistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers': {
      id: '/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof CoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers/': {
      id: '/covers/'
      path: '/'
      fullPath: '/covers/'
      preLoaderRoute: typeof CoversIndexRouteImport
      parentRoute: typeof CoversRoute
    }
    '/covers/$coverId': {
      id: '/covers/$coverId'
      path: '/$coverId'
      fullPath: '/covers/$coverId'
      preLoaderRoute: typeof CoversCoverIdRouteImport
      parentRoute: typeof CoversRoute
    }
  }
}

interface CoversRouteChildren {
  CoversCoverIdRoute: typeof CoversCoverIdRoute
  CoversIndexRoute: typeof CoversIndexRoute
}

const CoversRouteChildren: CoversRouteChildren = {
  CoversCoverIdRoute: CoversCoverIdRoute,
  CoversIndexRoute: CoversIndexRoute,
}

const CoversRouteWithChildren =
  CoversRoute._addFileChildren(CoversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoversRoute: CoversRouteWithChildren,
  PlaylistsRoute: PlaylistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
