/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or
// formatter to prevent it from being checked or modified.
//
// A committed copy is included so the project type-checks on a fresh clone; the
// Vite plugin (vite.config.ts) regenerates it on `dev`/`build`.

import { Route as rootRoute } from './routes/__root'
import { Route as PlaylistsImport } from './routes/playlists'
import { Route as CoversImport } from './routes/covers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PlaylistsRoute = PlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any)

const CoversRoute = CoversImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/covers': {
      id: '/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof CoversImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

const rootRouteChildren = {
  IndexRoute,
  CoversRoute,
  PlaylistsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()
