#!/usr/bin/env bash
#
# dev-setup.sh — generate the local development configuration.
#
# Aurify requires a mail relay and a signing key in every environment; there is
# no development exemption, because development substitutes real infrastructure
# (Mailpit) rather than asking the application to behave differently. That makes
# an unsafe configuration unrepresentable, but it does mean a fresh clone needs
# its own secrets generated once. This does that.
#
# The generated file is gitignored.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT_DIR/backend/.env.dev"

if [[ -f "$TARGET" && "${1:-}" != "--force" ]]; then
  echo "✓ $TARGET already exists (pass --force to regenerate)"
  exit 0
fi

if ! command -v base64 >/dev/null 2>&1; then
  echo "✗ base64 is required to generate a signing key" >&2
  exit 1
fi

SIGNING_KEY="$(head -c 32 /dev/urandom | base64)"

cat > "$TARGET" <<CONFIG
# Local development configuration, generated by scripts/dev-setup.sh.
# Gitignored. Regenerate with: ./scripts/dev-setup.sh --force

# Mail goes to Mailpit, a real SMTP server running in docker-compose. Read what
# was "sent" at http://localhost:8025. The application takes exactly the same
# code path here as it does against SMTP2GO in production.
AURIFY_SMTP_HOST=mailpit
AURIFY_SMTP_PORT=1025
AURIFY_SMTP_FROM=no-reply@aurify.local
# Mailpit does not terminate TLS. Safe only because it is on this machine and
# takes no credentials; the sender refuses to send a username without TLS.
AURIFY_SMTP_TLS=false

# Stable so sessions survive a container restart. Local only; never reuse it.
AURIFY_AUTH_SIGNING_KEY=$SIGNING_KEY

# Browsers drop a Secure cookie sent over plain http, which makes sign-in appear
# to succeed while nothing is authenticated. Off for local http only.
AURIFY_AUTH_COOKIE_SECURE=false

AURIFY_SUPPORT_EMAIL=support@aurify.local

# Google sign-in stays disabled until you supply a client; its routes answer 501
# and the rest of auth works normally.
# AURIFY_GOOGLE_CLIENT_ID=
# AURIFY_GOOGLE_CLIENT_SECRET=
# Points at the Vite dev server, not the API's own port. Vite proxies /api to
# localhost:8080, so the callback lands on the same origin the app runs on,
# which is what production does. Register this exact string in Google Cloud.
AURIFY_GOOGLE_REDIRECT_URL=http://localhost:5173/api/v1/auth/federated/google/callback
CONFIG

echo "✓ wrote $TARGET"
echo "  next: ./start_container.sh -d   then open http://localhost:8025 for mail"
